In [1]:
mylist = ['red', 'blue', 'green', 1, (1,2), [1,2]]

In [2]:
mylist

['red', 'blue', 'green', 1, (1, 2), [1, 2]]

In [7]:
mylist[5][-1]

2

In [11]:
# Tuple

In [12]:
# Immutable
t = 1,

In [13]:
type(t)

tuple

In [14]:
t

(1,)

In [15]:
t = (5)

In [16]:
t

5

In [17]:
type(t)

int

In [18]:
t = (5,1)

In [1]:
d = {'A': 'a', 'B': 'b'}

In [9]:
d.pop('A')

'a'

In [10]:
d

{'B': 'b'}

In [11]:
## NumPy - Numerical Python


In [12]:
import numpy as np

In [13]:
np.__version__

'1.21.5'

In [14]:
hieghts = [1,2,3,4]

In [15]:
hieghts * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
np_hieghts = np.array(hieghts)

In [17]:
np_hieghts * 2

array([2, 4, 6, 8])

In [18]:
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71]

weights_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180]

In [21]:
height_meter = np.array(height_in) * 0.0254
height_meter

array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.7526, 1.7526, 1.8034,
       1.9304, 1.8034])

In [22]:
weights_arr = np.array(weights_lb)

In [24]:
weights_kgs = weights_arr * 0.4535
weights_kgs

array([ 81.63  ,  97.5025,  95.235 ,  95.235 ,  85.258 ,  79.816 ,
        94.7815,  90.7   , 104.7585,  81.63  ])

In [25]:
# body Mass Index
BMI = weights_kgs/height_meter**2

In [26]:
BMI

array([23.10568902, 27.59846188, 28.47502801, 28.47502801, 24.79830443,
       25.98509713, 30.85730284, 27.88837159, 28.11218832, 25.09953443])

In [31]:
BMI > 25

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [32]:
BMI[BMI > 25]

array([27.59846188, 28.47502801, 28.47502801, 25.98509713, 30.85730284,
       27.88837159, 28.11218832, 25.09953443])

In [33]:
height_meter[BMI > 25]

array([1.8796, 1.8288, 1.8288, 1.7526, 1.7526, 1.8034, 1.9304, 1.8034])

In [35]:
weights_kgs[BMI > 25]

array([ 97.5025,  95.235 ,  95.235 ,  79.816 ,  94.7815,  90.7   ,
       104.7585,  81.63  ])

In [36]:
BMI[0]

23.10568901634516

In [37]:
BMI[-1]

25.099534428388438

In [38]:
np.max(BMI)

30.85730284041959

In [39]:
np.min(BMI)

23.10568901634516

In [40]:
np.mean(BMI)

27.03950056627765

In [41]:
number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3]

price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195]

In [43]:
number_arr = np.array(number)

price_arr = np.array(price)

In [44]:
len(number_arr)

12

In [45]:
np.sum(number_arr)

76

In [46]:
np.average(price_arr)

168.75

In [48]:
np.max(price_arr)

270

In [51]:
np.sum(number_arr * price_arr)

12690

In [54]:
np.max(price_arr)

270

In [65]:
price_arr == np.max(price_arr)

array([False, False, False, False, False, False, False, False,  True,
       False, False, False])

In [66]:
number_arr[price_arr == np.max(price_arr)]

array([3])